-- most_popular_transport_types
SELECT TFL.JOURNEYS.JOURNEY_TYPE AS JOURNEY_TYPE, SUM(TFL.JOURNEYS.JOURNEYS_MILLIONS) AS TOTAL_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
GROUP BY JOURNEY_TYPE
ORDER BY TOTAL_JOURNEYS_MILLIONS DESC;