-- emirates_airline_popularity
SELECT TFL.JOURNEYS.MONTH, TFL.JOURNEYS.YEAR, ROUND(TFL.JOURNEYS.JOURNEYS_MILLIONS, 2) AS ROUNDED_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
WHERE TFL.JOURNEYS.JOURNEY_TYPE = 'Emirates Airline' AND TFL.JOURNEYS.JOURNEYS_MILLIONS IS NOT NULL
ORDER BY TFL.JOURNEYS.JOURNEYS_MILLIONS DESC
LIMIT 5;