-- least_popular_years_tube
SELECT TFL.JOURNEYS.YEAR, 'Underground & DLR' AS JOURNEY_TYPE, SUM(TFL.JOURNEYS.JOURNEYS_MILLIONS) AS TOTAL_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
WHERE TFL.JOURNEYS.JOURNEY_TYPE = 'Underground & DLR'
GROUP BY TFL.JOURNEYS.YEAR
ORDER BY TOTAL_JOURNEYS_MILLIONS ASC
LIMIT 5;